import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { VitalReading, HealthPrediction } from '../lib/supabase';
import { format } from 'date-fns';

export interface HealthReportData {
  user: {
    name: string;
    age?: number;
    gender?: string;
  };
  vitals: VitalReading[];
  predictions: HealthPrediction[];
  dateRange: {
    start: string;
    end: string;
  };
}

export async function generateHealthReport(data: HealthReportData): Promise<void> {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  
  // Header
  pdf.setFontSize(24);
  pdf.setTextColor(88, 28, 135); // Purple
  pdf.text('HealthAI Monitor Report', pageWidth / 2, 30, { align: 'center' });
  
  // Patient Info
  pdf.setFontSize(16);
  pdf.setTextColor(0, 0, 0);
  pdf.text('Patient Information', 20, 60);
  
  pdf.setFontSize(12);
  pdf.text(`Name: ${data.user.name}`, 20, 75);
  if (data.user.age) pdf.text(`Age: ${data.user.age}`, 20, 85);
  if (data.user.gender) pdf.text(`Gender: ${data.user.gender}`, 20, 95);
  pdf.text(`Report Period: ${format(new Date(data.dateRange.start), 'MMM dd, yyyy')} - ${format(new Date(data.dateRange.end), 'MMM dd, yyyy')}`, 20, 105);
  
  // Summary Statistics
  if (data.vitals.length > 0) {
    const avgHeartRate = Math.round(data.vitals.reduce((sum, v) => sum + v.heart_rate, 0) / data.vitals.length);
    const avgSpo2 = Math.round(data.vitals.reduce((sum, v) => sum + v.spo2, 0) / data.vitals.length);
    const avgTemp = (data.vitals.reduce((sum, v) => sum + v.temperature, 0) / data.vitals.length).toFixed(1);
    
    pdf.setFontSize(16);
    pdf.text('Vital Signs Summary', 20, 130);
    
    pdf.setFontSize(12);
    pdf.text(`Average Heart Rate: ${avgHeartRate} bpm`, 20, 145);
    pdf.text(`Average SpO₂: ${avgSpo2}%`, 20, 155);
    pdf.text(`Average Temperature: ${avgTemp}°C`, 20, 165);
    pdf.text(`Total Readings: ${data.vitals.length}`, 20, 175);
  }
  
  // Risk Assessment
  if (data.predictions.length > 0) {
    const riskCounts = data.predictions.reduce((acc, p) => {
      acc[p.risk_level] = (acc[p.risk_level] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);
    
    pdf.setFontSize(16);
    pdf.text('Risk Assessment Summary', 20, 200);
    
    pdf.setFontSize(12);
    let yPos = 215;
    Object.entries(riskCounts).forEach(([level, count]) => {
      pdf.text(`${level}: ${count} assessments`, 20, yPos);
      yPos += 10;
    });
  }
  
  // Recent Predictions
  if (data.predictions.length > 0) {
    pdf.addPage();
    pdf.setFontSize(16);
    pdf.text('Recent Health Assessments', 20, 30);
    
    let yPos = 50;
    data.predictions.slice(0, 5).forEach((prediction, index) => {
      if (yPos > pageHeight - 50) {
        pdf.addPage();
        yPos = 30;
      }
      
      pdf.setFontSize(14);
      pdf.text(`Assessment ${index + 1}`, 20, yPos);
      yPos += 15;
      
      pdf.setFontSize(12);
      pdf.text(`Date: ${format(new Date(prediction.created_at), 'MMM dd, yyyy HH:mm')}`, 20, yPos);
      yPos += 10;
      pdf.text(`Risk Level: ${prediction.risk_level}`, 20, yPos);
      yPos += 10;
      pdf.text(`Risk Score: ${prediction.risk_score}/100`, 20, yPos);
      yPos += 10;
      pdf.text(`Confidence: ${prediction.confidence}%`, 20, yPos);
      yPos += 15;
      
      if (prediction.predicted_conditions.length > 0) {
        pdf.text('Identified Conditions:', 20, yPos);
        yPos += 10;
        prediction.predicted_conditions.forEach(condition => {
          pdf.text(`• ${condition}`, 25, yPos);
          yPos += 8;
        });
        yPos += 5;
      }
      
      if (prediction.recommendations.length > 0) {
        pdf.text('Recommendations:', 20, yPos);
        yPos += 10;
        prediction.recommendations.forEach(rec => {
          const lines = pdf.splitTextToSize(`• ${rec}`, pageWidth - 50);
          pdf.text(lines, 25, yPos);
          yPos += lines.length * 8;
        });
      }
      
      yPos += 20;
    });
  }
  
  // Footer
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(10);
    pdf.setTextColor(128, 128, 128);
    pdf.text(`Generated by HealthAI Monitor - Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    pdf.text(`Generated on ${format(new Date(), 'MMM dd, yyyy HH:mm')}`, pageWidth / 2, pageHeight - 20, { align: 'center' });
  }
  
  // Save the PDF
  pdf.save(`health-report-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
}